name: Quick test on ubuntu-latest

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Get tools
      run: sudo apt-get install -yqq g++ cmake make tar wget
 
    - name: Get oneTBB
      run: wget https://github.com/oneapi-src/oneTBB/releases/download/v2021.1-beta10/oneapi-tbb-2021.1-beta10-lin.tgz && tar xaf oneapi-tbb-2021.1-beta10-lin.tgz

    - name: Configure, build and test
      run: |
        mkdir build && cd build && cmake -DTBB_DIR=${GITHUB_WORKSPACE}/oneapi-tbb-2021.1-beta10/lib/intel64/cmake/TBB ..
        make -j4 VERBOSE=1 build-all
        ctest --output-on-failure
